# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
pod 'Firebase/Core'

target 'MemeCreator' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MemeCreator

  target 'MemeCreator-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MemeCreatorTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

